---
title: Mapping the 21st Century with Hendrix Students
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@domain.com
author: GitHub User
copyright: Unpublished Work (cleft) 2017-{currentYear} {author}
description: |-
  "A showcase for Hendrix students to highlight their work with Geographic
    Information Systems (GIS) and to share these datasets. We emphasize work in Anthropology
    and Environmental Studies, focusing especially on questions of environmental justice.
    The entries here are authored by students and are based on work that they have done
    in their undergraduate studies at Hendrix. \n"
baseurl: ''
url: ''
favicon: ''
yat:
  date_format: "%b %d, %Y"
markdown: kramdown
kmarkdown:
  input: GFM
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-paginate
- jekyll-spaceship
